### ISSUE TITLE
PC sheets missing sidebar bg, illegible, w/ no window app theme

### ISSUE THREAD

**Issue by SoulCookie** [Dorako/pf2e-dorako-ui#278]
When I have the "Window App Theme" set to "No Theme," the player characters' actor sheets are missing the background color along the lefthand edge. Whatever is **supposed** to be overriding the default PF2e red strip isn't, but only with the "No Theme" setting; the three others, such as "Core Rulebook," all properly style the sheet according to my "PC Sheet Theme" setting.

- Dorako UI 3.1.2
- Dorako UX 1.1.1
- Foundry 11.315 [hosted at Forge]
- PF2e system 5.9.5

WINDOW APP THEME = NO THEME
![foundry_mod-dorako-ui_bug-PC-sheet-sidebar_no-window-app-theme](https://github.com/Dorako/pf2e-dorako-ui/assets/4214704/cc8f3413-311c-46a2-b7e4-02a8ac1da22c)

WINDOW APP THEME = CORE RULEBOOK 
![foundry_mod-dorako-ui_bug-PC-sheet-sidebar_CRB-window-app-theme](https://github.com/Dorako/pf2e-dorako-ui/assets/4214704/a2df2a44-73b9-4ccb-a366-9d18c8512038)

![foundry_mod-dorako-ui_bug-PC-sheet-sidebar_module-settings](https://github.com/Dorako/pf2e-dorako-ui/assets/4214704/06041c8e-21c2-4e21-8824-3853b5a07432)

**Comment by Dorako** [comment]
Can you try without Dorako UI enabled?
When "no theme" is selected, that means that Dorako UI shouldn't be affected the player sheets at all - thus also not making them green, so that's expected.
As such, the red backdrop you're missing I would expected to be the red backdrop shipped by the system.
If the issue persists with Dorako UI disabled, try reinstalling the system.
Here's a picture with "no window app theme" and "green sheet" selected:
![CleanShot 2023-11-26 at 01 37 28@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/cccafb0e-7745-4f75-8389-6cb829de0162)

**Comment by Dorako** [comment]
Just had one more person using the forge with a similar issue which was resolved by some combination of disabling/reinstalling/hard-refreshing to reset cache.

**Comment by SoulCookie** [comment]
I know you think this bug isn't a thing, but I promise you it's still happening to me.

The background styling of the <aside> sidebar is erroneously calling an absolute path URL to assets that don't exist.

```
.actor.sheet .crb-style aside {
  background-image: var(--sheet-sidebar-color-bg);
}
```

What the variable ends up looking for:

```
url("https://[my game identifier].forge-vtt.com/modules/pf2e-dorako-ui/img/red_sidebar_top.webp"), url("https://[my game identifier].forge-vtt.com/modules/pf2e-dorako-ui/img/red_sidebar_bottom.webp")
```

**Comment by Dorako** [comment]
np, glad you figured it out
